---

- hosts: all
  become: true

- hosts: JOBS
  become: true
  tasks:
  - name: create a folder named "BackUpFor_ FIRE14WIN-SP-OTH-2022012"
    win_file:
      path: 'E:\IRS\BackUpFor_ FIRE14WIN-SP-OTH-2022012'
      state: directory
  - name: backup files into backup folder
    win_copy:
      src: E:\IRS\FIRE_Backend_Programs_Deploy.msi
      dest: 'E:\IRS\BackUpFor_ FIRE14WIN-SP-OTH-2022012\FIRE_Backend_Programs_Deploy.msi'
  - name: copy files into backend
    win_copy:
      src: 'E:\IRS\FIRE Backend Programs\FIRE_Backend_Programs_Deploy.msi'
      dest: E:\IRS\FIRE_Backend_Programs_Deploy.msi

- hosts: SQL
  become: true
  tasks:
  - name: create a folder named "BackUpFor_ FIRE14WIN-SP-OTH-2022012"
    win_file:
      path: 'E:\IRS\BackUpFor_ FIRE14WIN-SP-OTH-2022012'
      state: directory
  - name: backup files into backup folder
    win_copy:
      src: E:\IRS\FIRE_Backend_Programs_Deploy.msi
      dest: 'E:\IRS\BackUpFor_ FIRE14WIN-SP-OTH-2022012\FIRE_Backend_Programs_Deploy.msi'
  - name: copy files into backend
    win_copy:
      src: 'E:\IRS\FIRE Backend Programs\FIRE_Backend_Programs_Deploy.msi'
      dest: E:\IRS\FIRE_Backend_Programs_Deploy.msi
  - name: uninstall FIRE Backend Programs
    win_package:
      path: E:\IRS\FIRE_Backend_Programs_Deploy.msi
      state: present
  - name: back-out plan
    win_shell: copy 'E:\IRS\BackUpFor_ FIRE14WIN-SP-OTH-2022012\FIRE_Backend_Programs_Deploy.msi' E:\IRS\FIRE_Backend_Programs_Deploy.msi
    args:
      executable: cmd.exe
  - name: perform install/uninstall again
    win_package:
      path: E:\IRS\FIRE_Backend_Programs_Deploy.msi
      state: present
  - name: uncomment PROD CSR background color
    community.windows.win_lineinfile:
       path: E:\UI.css
       regex: '/*background-color: #ffffe8 /*Production Color*/'
       line: 'background-color: #ffffe8 /*Production Color*/'
  - name: comment TPTest Color
    community.windows.win_lineinfile:
       path: E:\UI.css
       regex: 'background-color: #FFE4E1 /*TPTest Color*/'
       line: '/*background-color: #FFE4E1 /*TPTest Color*/'

- hosts: JOBS
  become: true
  roles:
    - TPT_Servers_Role

- hosts: SQL
  become: true
  roles:
    - TPT_Servers_Role
