---

- hosts: JOBS
  become: true
  tasks:
  - name: create a folder named "BackUpFor_ FIRE14WIN-SP-OTH-2022012"
    win_file:
      path: 'E:\IRS\BackUpFor_ FIRE14WIN-SP-OTH-2022012'
      state: directory
  - name: backup files into backup folder
    win_copy:
      src: E:\IRS\FIRE_Backend_Programs_Deploy.msi
      dest: 'E:\IRS\BackUpFor_ FIRE14WIN-SP-OTH-2022012\FIRE_Backend_Programs_Deploy.msi'
  - name: copy files into backend
    win_copy:
      src: 'E:\IRS\FIRE Backend Programs\FIRE_Backend_Programs_Deploy.msi'
      dest: E:\IRS\FIRE_Backend_Programs_Deploy.msi

- hosts: SQL
  become: true
  tasks:
  - name: create a folder named "BackUpFor_ FIRE14WIN-SP-OTH-2022012"
    win_file:
      path: 'E:\IRS\BackUpFor_ FIRE14WIN-SP-OTH-2022012'
      state: directory
  - name: backup files into backup folder
    win_copy:
      src: E:\IRS\FIRE_Backend_Programs_Deploy.msi
      dest: 'E:\IRS\BackUpFor_ FIRE14WIN-SP-OTH-2022012\FIRE_Backend_Programs_Deploy.msi'
  - name: copy files into backend
    win_copy:
      src: 'E:\IRS\FIRE Backend Programs\FIRE_Backend_Programs_Deploy.msi'
      dest: E:\IRS\FIRE_Backend_Programs_Deploy.msi
  - name: uninstall FIRE Backend Programs
    win_package:
      path: E:\IRS\FIRE_Backend_Programs_Deploy.msi
      state: absent
  - name: back-out plan
    win_shell: copy 'E:\IRS\BackUpFor_ FIRE14WIN-SP-OTH-2022012\FIRE_Backend_Programs_Deploy.msi' E:\IRS\FIRE_Backend_Programs_Deploy.msi
    args:
      executable: cmd.exe
  - name: perform install of backup
    win_package:
      path: E:\IRS\FIRE_Backend_Programs_Deploy.msi
      state: present
  - name: install ODBC driver required by sqlcmd
    win_package:
      path: 'https://go.microsoft.com/fwlink/?linkid=2214634' #url to ODBC driver
      state: present
    when: ansible_distribution == 'Windows'
  - name: install sqlcmd utility
    win_package:
      path: 'https://go.microsoft.com/fwlink/?linkid=2142258' #url to sqlcmd utility used for running SQL scripts from the command line
      state: present
    when: ansible_distribution == 'Windows'
  - name: run BOYSCRIPT.sql agains IRS_FIRE2 database
    win_command: "sqlcmd -U {{sql_login_user}} -P {{sql_pwd}} -d {{db_name}} -i {{script_name}}"
    register: sqmcmd_out
    when: ansible_distribution == 'Windows'
  - name: Find UI.css
    ansible.windows.win_find:
      paths: E:\IRS
      recurse: yes
      patterns: ['UI.css']
    register: ui_window_path
  - name: uncomment PROD CSS background color
    community.windows.win_lineinfile:
       path: "{{ui_window_path[0]}}"
       regex: '/\*background-color: #ffffe8 /\*Production Color\*/'
       line: 'background-color: #ffffe8 /*Production Color*/'
  - name: comment TPTest Color
    community.windows.win_lineinfile:
       path: "{{ui_window_path[0]}}"
       regex: 'background-color: #FFE4E1 /\*TPTest Color\*/'
       line: '/*background-color: #FFE4E1 /*TPTest Color*/'
  - name: Uninstall FIREv1R Presentation Layer
    win_package:
      path: "E:\\IRS\\firev1r presentation layer installer.msi"
      state: absent
  - name: Create physical path for virtual directory
    win_file:
      path: "E:\\virtualdirectory\\IRS"
      state: directory
  - name: Create Blank Virtual Directory
    community.windows.win_iis_virtualdirectory:
      name: Blank
      site: FIREv1r
      application: FIREv1rAppPool4.0
      state: present
      physical_path: "E:\\virtualdirectory\\IRS"

- hosts: JOBS
  become: true
  roles:
    - TPT_Servers_Role

- hosts: SQL
  become: true
  roles:
    - TPT_Servers_Role
